# Generated by Django 5.2.4 on 2025-07-15 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caixa', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloco', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('corrente', 'Corrente'), ('intermediario', 'Intermediário')], max_length=20)),
                ('data_arquivamento', models.DateField()),
                ('data_prevista_descarte', models.DateField()),
                ('arquivo_pdf', models.CharField(blank=True, max_length=255, null=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fito_backend.caixa')),
            ],
        ),
        migrations.CreateModel(
            name='Andar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('andar', models.IntegerField()),
                ('estante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fito_backend.estante')),
            ],
        ),
        migrations.CreateModel(
            name='Posicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.IntegerField()),
                ('andar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fito_backend.andar')),
            ],
        ),
        migrations.AddField(
            model_name='caixa',
            name='posicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fito_backend.posicao'),
        ),
        migrations.AddField(
            model_name='estante',
            name='rua',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fito_backend.rua'),
        ),
    ]
