# Generated by Django 5.2.4 on 2025-07-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fito_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
